import { Check, Eye, FileText, RefreshCw, Upload, UserRoundPlus, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'

import { DataTable } from '@/components/common/DataTable'
import { Modal } from '@/components/common/Modal'
import { PageHeader } from '@/components/common/PageHeader'
import { EmptyState } from '@/components/feedback/EmptyState'
import { ErrorState } from '@/components/feedback/ErrorState'
import { LoadingState } from '@/components/feedback/LoadingState'
import { Badge } from '@/components/ui/Badge'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { Input } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { Textarea } from '@/components/ui/Textarea'
import { useAsyncResource } from '@/hooks/useAsyncResource'
import { PrivateFileInput } from '@/modules/document-reviews/PrivateFileInput'
import { SecureAttachmentPreview as DocumentPreview } from '@/modules/document-reviews/SecureAttachmentPreview'
import { documentReviewRepository, type EligibleReviewer, type ReviewAttachment } from '@/services/supabase/documentReviewRepository'
import type { Database } from '@/types/database.types'

type Stage = 'faculty' | 'jury'
type Decision = Database['public']['Enums']['attachment_review_decision']
type Status = Database['public']['Enums']['attachment_verification_status']

const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())
const date = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'
const statusTone = (status: Status): 'primary' | 'success' | 'warning' | 'muted' => status === 'verified' ? 'success' : status.includes('rejected') || status === 'replaced' ? 'muted' : status.includes('pending') ? 'warning' : 'primary'

function StatusBadge({ status }: { status: Status }) { return <Badge tone={statusTone(status)}>{label(status)}</Badge> }

function Filters({ search, setSearch, status, setStatus, type, setType }: { search: string; setSearch: (value: string) => void; status: string; setStatus: (value: string) => void; type: string; setType: (value: string) => void }) {
  return <div className="grid gap-3 sm:grid-cols-[1fr_12rem_12rem]"><Input aria-label="Search documents" placeholder="Search student, registration, or filename" value={search} onChange={(event) => setSearch(event.target.value)} /><Select aria-label="Verification status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="pending_faculty_review">Pending Faculty</option><option value="pending_jury_review">Pending Jury</option></Select><Select aria-label="Document type" value={type} onChange={(event) => setType(event.target.value)}><option value="all">All document types</option><option value="project">Project</option><option value="competition">Competition</option><option value="request">Request</option><option value="announcement">Announcement</option></Select></div>
}

function ReviewDialog({ item, stage, onClose, onDone }: { item: ReviewAttachment; stage: Stage; onClose: () => void; onDone: (message: string) => Promise<void> }) {
  const [decision, setDecision] = useState<Decision>('approved'); const [comments, setComments] = useState(''); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const submit = async () => { if (!item) return; if (decision === 'rejected' && !comments.trim()) { setError('A rejection reason is required.'); return } setSubmitting(true); setError(''); try { if (stage === 'faculty') await documentReviewRepository.reviewAsFaculty(item.id, decision, comments); else await documentReviewRepository.reviewAsJury(item.id, decision, comments); await onDone(`${stage === 'faculty' ? 'Faculty' : 'Jury'} decision recorded.`); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to record the review.') } finally { setSubmitting(false) } }
  return <Modal isOpen={Boolean(item)} title={`${stage === 'faculty' ? 'Faculty' : 'Jury'} review`} onClose={onClose}>{item && <div className="space-y-4"><div className="rounded-lg bg-background p-3 text-sm"><p className="font-semibold text-text">{item.filename}</p><p className="mt-1 text-muted">{item.owner?.name ?? 'Student'} · {label(item.entity_type)}</p></div><label className="flex cursor-pointer items-center gap-2 text-sm"><input checked={decision === 'approved'} name="decision" type="radio" onChange={() => setDecision('approved')} /> Approve</label><label className="flex cursor-pointer items-center gap-2 text-sm"><input checked={decision === 'rejected'} name="decision" type="radio" onChange={() => setDecision('rejected')} /> Reject</label><label className="block text-sm font-semibold">{decision === 'rejected' ? 'Rejection reason *' : 'Review comment (optional)'}<Textarea className="mt-1" value={comments} onChange={(event) => setComments(event.target.value)} /></label>{error && <p role="alert" className="text-sm text-error">{error}</p>}<div className="flex justify-end gap-3"><Button variant="secondary" onClick={onClose} disabled={submitting}>Cancel</Button><Button variant={decision === 'rejected' ? 'danger' : 'primary'} onClick={() => void submit()} disabled={submitting}>{decision === 'approved' ? <Check className="size-4" /> : <X className="size-4" />}{submitting ? 'Submitting…' : decision === 'approved' ? 'Confirm approval' : 'Confirm rejection'}</Button></div></div>}</Modal>
}

function AttachmentHistory({ item }: { item: ReviewAttachment }) {
  const [history, setHistory] = useState<Array<{ id: string; action: string; createdAt: string; comment: string | null }>>([])
  useEffect(() => { let active = true; void documentReviewRepository.getAttachmentReviewHistory(item.id).then((data) => { if (active) setHistory(data) }).catch(() => { if (active) setHistory([]) }); return () => { active = false } }, [item.id])
  const current = [{ id: 'upload', action: 'uploaded', createdAt: item.created_at, comment: null }, item.faculty_reviewed_at ? { id: 'faculty', action: `faculty ${item.verification_status === 'faculty_rejected' ? 'rejected' : 'approved'}`, createdAt: item.faculty_reviewed_at, comment: item.faculty_review_comment } : null, item.jury_reviewed_at ? { id: 'jury', action: `jury ${item.verification_status === 'jury_rejected' ? 'rejected' : 'approved'}`, createdAt: item.jury_reviewed_at, comment: item.jury_review_comment } : null, item.replacement_for_attachment_id ? { id: 'replacement', action: 'replacement submitted', createdAt: item.created_at, comment: null } : null].filter((entry): entry is { id: string; action: string; createdAt: string; comment: string | null } => Boolean(entry))
  const entries = history.length ? history : current
  return <div className="border-t border-border pt-4"><h3 className="font-semibold text-text">Review history</h3><ol className="mt-3 space-y-3 border-l border-border pl-4">{entries.map((entry) => <li key={entry.id} className="text-sm"><p className="font-medium text-text">{label(entry.action)}</p><p className="text-xs text-muted">{date(entry.createdAt)}</p>{entry.comment && <p className="mt-1 text-muted">{entry.comment}</p>}</li>)}</ol></div>
}

function QueueCards({ rows, onPreview, onReview }: { rows: ReviewAttachment[]; onPreview: (row: ReviewAttachment) => void; onReview: (row: ReviewAttachment) => void }) { return <div className="grid gap-3 md:hidden">{rows.map((row) => <Card key={row.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-text">{row.filename}</p><p className="text-sm text-muted">{row.owner?.name ?? 'Student'}{row.owner?.registrationNumber ? ` · ${row.owner.registrationNumber}` : ''}</p></div><StatusBadge status={row.verification_status} /></div><p className="mt-3 text-sm text-muted">{label(row.entity_type)} · Uploaded {date(row.created_at)}</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" onClick={() => onPreview(row)}><Eye className="size-4" /> View</Button><Button onClick={() => onReview(row)}>Review</Button></div></Card>)}</div> }

export function DocumentReviewQueuePage({ stage }: { stage: Stage }) {
  const load = useCallback(() => stage === 'faculty' ? documentReviewRepository.getFacultyReviewQueue() : documentReviewRepository.getJuryReviewQueue(), [stage])
  const resource = useAsyncResource(load); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [type, setType] = useState('all'); const [preview, setPreview] = useState<ReviewAttachment | null>(null); const [reviewing, setReviewing] = useState<ReviewAttachment | null>(null); const [success, setSuccess] = useState('')
  const rows = useMemo(() => (resource.data ?? []).filter((row) => { const text = `${row.filename} ${row.owner?.name ?? ''} ${row.owner?.registrationNumber ?? ''}`.toLowerCase(); return text.includes(search.toLowerCase()) && (status === 'all' || row.verification_status === status) && (type === 'all' || row.entity_type === type) }), [resource.data, search, status, type])
  const heading = stage === 'faculty' ? 'Faculty document reviews' : 'Jury document reviews'
  const done = async (message: string) => { setSuccess(message); await resource.reload() }
  return <div className="space-y-6"><PageHeader title={heading} description={stage === 'faculty' ? 'Review only documents assigned to you.' : 'Jury-eligible Faculty can review assigned second-stage documents.'} actions={<Button variant="secondary" onClick={() => void resource.reload()}><RefreshCw className="size-4" /> Refresh</Button>} />{success && <Card><p className="text-sm font-medium text-success">{success}</p></Card>}<Card><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold text-text">Pending queue <Badge tone="warning">{(resource.data ?? []).length}</Badge></h2></div><div className="mt-4"><Filters search={search} setSearch={setSearch} status={status} setStatus={setStatus} type={type} setType={setType} /></div></Card>{resource.isLoading ? <LoadingState label="Loading assigned documents…" /> : resource.error ? <ErrorState title="Unable to load document reviews" description={resource.error} /> : <><QueueCards rows={rows} onPreview={setPreview} onReview={setReviewing} /><div className="hidden md:block"><DataTable rows={rows} empty={<EmptyState title="No documents need your review" description="Assigned documents will appear here." />} columns={[{ header: 'Student', render: (row) => <div><p className="font-semibold">{row.owner?.name ?? 'Student'}</p><p className="text-xs text-muted">{row.owner?.registrationNumber ?? '—'}</p></div> }, { header: 'Document', render: (row) => <div><p>{row.filename}</p><p className="text-xs text-muted">{label(row.entity_type)} · {date(row.created_at)}</p></div> }, { header: 'Status', render: (row) => <StatusBadge status={row.verification_status} /> }, { header: 'Reviewers', render: (row) => <span className="text-xs">Faculty: {row.facultyReviewer?.name ?? 'Unassigned'}{row.requires_jury_review && <><br />Jury: {row.juryReviewer?.name ?? 'Unassigned'}</>}</span> }, { header: 'Action', render: (row) => <div className="flex gap-2"><Button className="min-h-8 px-3" variant="secondary" onClick={() => setPreview(row)}><Eye className="size-4" /></Button><Button className="min-h-8 px-3" onClick={() => setReviewing(row)}>Review</Button></div> }]} /></div></>}{preview && <DocumentPreview key={preview.id} attachment={preview} onClose={() => setPreview(null)} />}{reviewing && <ReviewDialog key={reviewing.id} item={reviewing} stage={stage} onClose={() => setReviewing(null)} onDone={done} />}</div>
}

function AssignmentDialog({ item, reviewers, onClose, onDone }: { item: ReviewAttachment; reviewers: EligibleReviewer[]; onClose: () => void; onDone: () => Promise<void> }) {
  const [facultyId, setFacultyId] = useState(item.faculty_reviewer_id ?? ''); const [juryId, setJuryId] = useState(item.jury_reviewer_id ?? ''); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const eligible = reviewers.filter((reviewer) => reviewer.id !== item?.owner_id); const jury = eligible.filter((reviewer) => reviewer.isJuryEligible)
  const save = async () => { if (!item) return; if (!facultyId) { setError('Select an active Faculty reviewer.'); return } if (item.requires_jury_review && !juryId) { setError('A Jury reviewer is required for this document.'); return } if (juryId && juryId === facultyId) { setError('Faculty and Jury reviewers must be different people.'); return } setSubmitting(true); setError(''); try { await documentReviewRepository.assignReviewers(item.id, facultyId, juryId || undefined); await onDone(); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to assign reviewers.') } finally { setSubmitting(false) } }
  return <Modal isOpen={Boolean(item)} title="Assign document reviewers" onClose={onClose}>{item && <div className="space-y-4"><p className="text-sm text-muted">{item.filename} · {item.owner?.name ?? 'Student'}</p><label className="block text-sm font-semibold">Faculty reviewer<Select className="mt-1" value={facultyId} onChange={(event) => setFacultyId(event.target.value)}><option value="">Select active Faculty</option>{eligible.map((reviewer) => <option key={reviewer.id} value={reviewer.id}>{reviewer.name}{reviewer.isJuryEligible ? ' (Jury eligible)' : ''}</option>)}</Select></label>{item.requires_jury_review && <label className="block text-sm font-semibold">Jury reviewer<Select className="mt-1" value={juryId} onChange={(event) => setJuryId(event.target.value)}><option value="">Select Jury-eligible Faculty</option>{jury.map((reviewer) => <option key={reviewer.id} value={reviewer.id}>{reviewer.name}</option>)}</Select></label>}{error && <p role="alert" className="text-sm text-error">{error}</p>}<div className="flex justify-end gap-3"><Button variant="secondary" disabled={submitting} onClick={onClose}>Cancel</Button><Button disabled={submitting} onClick={() => void save()}>{submitting ? 'Saving…' : 'Assign reviewers'}</Button></div></div>}</Modal>
}

export function ReviewerAssignmentPage() {
  const queue = useAsyncResource(useCallback(() => documentReviewRepository.getAssignmentQueue(), [])); const reviewers = useAsyncResource(useCallback(() => documentReviewRepository.getEligibleReviewers(), [])); const [selected, setSelected] = useState<ReviewAttachment | null>(null); const [success, setSuccess] = useState('')
  const done = async () => { setSuccess('Reviewers assigned successfully.'); await queue.reload() }
  return <div className="space-y-6"><PageHeader title="Document reviewer assignment" description="Assign active Faculty and, where required, Jury-eligible reviewers." actions={<Button variant="secondary" onClick={() => { void queue.reload(); void reviewers.reload() }}><RefreshCw className="size-4" /> Refresh</Button>} />{success && <Card><p className="text-sm font-medium text-success">{success}</p></Card>}{queue.isLoading || reviewers.isLoading ? <LoadingState label="Loading document assignment queue…" /> : queue.error || reviewers.error ? <ErrorState title="Unable to load reviewer assignment" description={queue.error ?? reviewers.error ?? undefined} /> : <><div className="grid gap-3 md:hidden">{(queue.data ?? []).map((item) => <Card key={item.id}><p className="font-semibold text-text">{item.filename}</p><p className="mt-1 text-sm text-muted">{item.owner?.name ?? 'Student'} · {item.requires_jury_review ? 'Jury review required' : 'Faculty review only'}</p><Button className="mt-4" onClick={() => setSelected(item)}><UserRoundPlus className="size-4" /> Assign</Button></Card>)}</div><div className="hidden md:block"><DataTable rows={queue.data ?? []} empty={<EmptyState title="No pending documents need reviewer assignment" />} columns={[{ header: 'Document', render: (item) => <div><p>{item.filename}</p><p className="text-xs text-muted">{label(item.entity_type)}</p></div> }, { header: 'Student', render: (item) => item.owner?.name ?? 'Student' }, { header: 'Review needs', render: (item) => item.requires_jury_review ? 'Faculty + Jury' : 'Faculty' }, { header: 'Current assignment', render: (item) => <span className="text-xs">{item.facultyReviewer?.name ?? 'Faculty unassigned'}{item.requires_jury_review && <><br />{item.juryReviewer?.name ?? 'Jury unassigned'}</>}</span> }, { header: 'Action', render: (item) => <Button className="min-h-8 px-3" onClick={() => setSelected(item)}>Assign</Button> }]} /></div></>}{selected && <AssignmentDialog key={selected.id} item={selected} reviewers={reviewers.data ?? []} onClose={() => setSelected(null)} onDone={done} />}</div>
}

function ReplacementDialog({ item, onClose, onDone }: { item: ReviewAttachment; onClose: () => void; onDone: () => Promise<void> }) {
  const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(''); const [progress, setProgress] = useState<number | null>(null)
  const upload = async () => { if (!item || !file) { setError('Choose a PDF, JPEG, or PNG document to continue.'); return } setError(''); setProgress(0); try { await documentReviewRepository.uploadReplacementAttachment(item, file, setProgress); await onDone(); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to upload the replacement.') } finally { setProgress(null) } }
  return <Modal isOpen={Boolean(item)} title="Upload replacement document" onClose={onClose}>{item && <div className="space-y-4"><p className="text-sm text-muted">Replacing rejected document: {item.filename}</p><PrivateFileInput label="New replacement file" file={file} onFile={setFile} onError={setError} disabled={progress !== null} />{progress !== null && <p className="text-sm text-muted">Uploading replacement… {progress}%</p>}{error && <p role="alert" className="text-sm text-error">{error}</p>}<div className="flex justify-end gap-3"><Button variant="secondary" disabled={progress !== null} onClick={onClose}>Cancel</Button><Button disabled={progress !== null || !file} onClick={() => void upload()}><Upload className="size-4" /> Submit replacement</Button></div></div>}</Modal>
}

export function StudentDocumentStatusPage() {
  const resource = useAsyncResource(useCallback(() => documentReviewRepository.getStudentAttachments(), [])); const [preview, setPreview] = useState<ReviewAttachment | null>(null); const [replacement, setReplacement] = useState<ReviewAttachment | null>(null); const [detail, setDetail] = useState<ReviewAttachment | null>(null); const [success, setSuccess] = useState('')
  const done = async () => { setSuccess('Replacement submitted for Faculty review.'); await resource.reload() }
  return <div className="space-y-6"><PageHeader title="My document verification" description="Track verification and replace rejected documents when requested." actions={<Button variant="secondary" onClick={() => void resource.reload()}><RefreshCw className="size-4" /> Refresh</Button>} />{success && <Card><p className="text-sm font-medium text-success">{success}</p></Card>}{resource.isLoading ? <LoadingState label="Loading your document verification…" /> : resource.error ? <ErrorState title="Unable to load document verification" description={resource.error} /> : <div className="grid gap-4 lg:grid-cols-2">{(resource.data ?? []).map((item) => <Card key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-text">{item.filename}</p><p className="mt-1 text-sm text-muted">{label(item.entity_type)} · Uploaded {date(item.created_at)}</p></div><StatusBadge status={item.verification_status} /></div><div className="mt-4 space-y-1 text-sm text-muted"><p>Faculty: {item.faculty_reviewed_at ? label(item.verification_status === 'faculty_rejected' ? 'rejected' : 'review complete') : 'Pending review'}</p>{item.requires_jury_review && <p>Jury: {item.jury_reviewed_at ? label(item.verification_status === 'jury_rejected' ? 'rejected' : 'review complete') : 'Pending or awaiting Faculty approval'}</p>}{(item.verification_status === 'faculty_rejected' || item.verification_status === 'jury_rejected') && <p className="pt-1 text-text">Reason: {item.verification_status === 'faculty_rejected' ? item.faculty_review_comment ?? 'No reason provided.' : item.jury_review_comment ?? 'No reason provided.'}</p>}</div><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" onClick={() => setPreview(item)}><Eye className="size-4" /> View</Button><Button variant="secondary" onClick={() => setDetail(item)}><FileText className="size-4" /> History</Button>{item.is_active && (item.verification_status === 'faculty_rejected' || item.verification_status === 'jury_rejected') && <Button onClick={() => setReplacement(item)}><Upload className="size-4" /> Replace</Button>}</div></Card>)}{!(resource.data ?? []).length && <div className="lg:col-span-2"><EmptyState title="No documents uploaded yet" description="Your uploaded documents and verification status will appear here." /></div>}</div>}{preview && <DocumentPreview key={preview.id} attachment={preview} onClose={() => setPreview(null)} />}{replacement && <ReplacementDialog key={replacement.id} item={replacement} onClose={() => setReplacement(null)} onDone={done} />}<Modal isOpen={Boolean(detail)} title="Document review history" onClose={() => setDetail(null)}>{detail && <AttachmentHistory item={detail} />}</Modal></div>
}
