import { Bell, Mail, Paperclip, Plus, RefreshCw, Search } from 'lucide-react'
import { useCallback, useState } from 'react'
import { useLocation } from 'react-router-dom'

import { DataTable } from '@/components/common/DataTable'
import { Modal } from '@/components/common/Modal'
import { PageHeader } from '@/components/common/PageHeader'
import { EmptyState } from '@/components/feedback/EmptyState'
import { ErrorState } from '@/components/feedback/ErrorState'
import { LoadingState } from '@/components/feedback/LoadingState'
import { Badge } from '@/components/ui/Badge'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { Input } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { Textarea } from '@/components/ui/Textarea'
import { USER_ROLES } from '@/constants/roles'
import { useAsyncResource } from '@/hooks/useAsyncResource'
import { useAuth } from '@/modules/auth/useAuth'
import { PrivateFileInput } from '@/modules/document-reviews/PrivateFileInput'
import { SecureAttachmentPreview } from '@/modules/document-reviews/SecureAttachmentPreview'
import { departmentOperationsRepository, isComplaintAssigneeProfile, type AnnouncementRecord, type ComplaintRecord, type MessageRecord, type OperationsData } from '@/services/supabase/departmentOperationsRepository'
import type { AttachmentRow } from '@/services/supabase/privateFileRepository'

const audiences = ['department', 'faculty', 'students', 'lab_assistants', 'section', 'assigned_students'] as const
type AnnouncementAudience = (typeof audiences)[number]
const publishAudiences = (role: string | undefined): readonly AnnouncementAudience[] => {
  if (role === USER_ROLES.faculty) return ['assigned_students']
  if (role === USER_ROLES.labAssistant) return ['department', 'section', 'assigned_students']
  return audiences
}
const tone = (value: string): 'primary' | 'success' | 'warning' | 'muted' => value === 'resolved' || value === 'read' ? 'success' : value === 'submitted' || value === 'in_review' || value === 'high' || value === 'unread' ? 'warning' : 'primary'
const initialAnnouncement = () => ({ id: '', title: '', message: '', category: 'Academic', priority: 'normal' as 'low' | 'normal' | 'high', audience: 'department', targetId: '', publishDate: new Date().toISOString().slice(0, 10), expiryDate: '', file: null as File | null })
const initialComplaint = () => ({ category: 'Infrastructure', subject: '', description: '', file: null as File | null })

export function CommunicationPage() {
  const { currentUser } = useAuth()
  const location = useLocation()
  const load = useCallback(() => departmentOperationsRepository.load(), [])
  const resource = useAsyncResource(load)
  const [announcementOpen, setAnnouncementOpen] = useState(false)
  const [complaintOpen, setComplaintOpen] = useState(false)
  const [messageOpen, setMessageOpen] = useState(false)
  const [reviewing, setReviewing] = useState<ComplaintRecord | null>(null)
  const [preview, setPreview] = useState<AttachmentRow | null>(null)
  const [announcement, setAnnouncement] = useState(initialAnnouncement)
  const [complaint, setComplaint] = useState(initialComplaint)
  const [message, setMessage] = useState({ recipientId: '', body: '' })
  const [review, setReview] = useState({ status: 'in_review' as 'in_review' | 'resolved', response: '', assignedTo: '' })
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('all')
  const [actionError, setActionError] = useState('')
  const [success, setSuccess] = useState('')
  const [saving, setSaving] = useState(false)

  const run = async (work: () => Promise<void>, notice: string) => {
    setActionError(''); setSuccess(''); setSaving(true)
    try { await work(); await resource.reload(); setSuccess(notice) } catch (error) { setActionError(error instanceof Error ? error.message : 'Unable to complete this action.') } finally { setSaving(false) }
  }

  const records = resource.data
  const role = currentUser?.role
  const canPublish = role === USER_ROLES.superAdmin || role === USER_ROLES.hod || role === USER_ROLES.faculty || role === USER_ROLES.labAssistant
  const announcementAudiences = publishAudiences(role)
  const canSubmitComplaint = role === USER_ROLES.student || role === USER_ROLES.faculty
  const canReviewComplaints = role === USER_ROLES.superAdmin || role === USER_ROLES.hod
  if (resource.isLoading) return <LoadingState label="Loading department operations…" />
  if (resource.error || !records || !currentUser) return <div className="space-y-3"><ErrorState title="Department operations unavailable" description={resource.error ?? 'Your session is unavailable.'} /><Button variant="secondary" onClick={() => void resource.reload()}>Retry</Button></div>
  if (role === USER_ROLES.student && location.pathname.endsWith('/announcements')) return <StudentAnnouncements records={records} userId={currentUser.id} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} saving={saving} run={run} reload={resource.reload} preview={preview} setPreview={setPreview} />

  const visibleAnnouncements = records.announcements.filter((item) => `${item.title} ${item.message} ${item.category}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || item.audience === filter))
  const visibleComplaints = records.complaints.filter((item) => `${item.subject} ${item.category} ${item.status}`.toLowerCase().includes(query.toLowerCase()))
  const visibleMessages = records.messages.filter((item) => item.message.toLowerCase().includes(query.toLowerCase()))
  const complaintAssignees = records.recipients.filter(isComplaintAssigneeProfile)

  const openAnnouncement = (item?: AnnouncementRecord) => {
    setActionError(''); setSuccess('')
    setAnnouncement(item ? { id: item.id, title: item.title, message: item.message, category: item.category, priority: item.priority as 'low' | 'normal' | 'high', audience: item.audience, targetId: audienceTarget(item), publishDate: item.publish_date, expiryDate: item.expiry_date ?? '', file: null } : { ...initialAnnouncement(), audience: announcementAudiences[0] })
    setAnnouncementOpen(true)
  }
  if (role === USER_ROLES.faculty) return <div className="space-y-6">
    <PageHeader title="Announcements" description="Faculty announcements and notices stay separate from request workflows." actions={<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => void resource.reload()}><RefreshCw className="size-4" /> Refresh</Button>{canPublish && <Button onClick={() => openAnnouncement()}><Plus className="size-4" /> Announcement</Button>}</div>} />
    {(actionError || success) && <div className="space-y-3">{actionError && <ErrorState title="Announcement needs attention" description={actionError} />}{success && <div role="status" className="rounded-xl border border-success/30 bg-success/5 p-4 text-sm font-medium text-text">{success}</div>}</div>}
    <Card><div className="grid gap-3 md:grid-cols-[1fr_12rem]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-muted" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search announcements" /></label><Select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All audiences</option>{audiences.map((audience) => <option key={audience} value={audience}>{audience.replace('_', ' ')}</option>)}</Select></div></Card>
    <Card><div className="flex items-center gap-3"><Bell className="size-5 text-secondary" /><div><h2 className="font-bold text-text">Announcements</h2><p className="text-sm text-muted">Audience visibility and author permissions are enforced by Supabase.</p></div></div><div className="mt-4"><DataTable rows={visibleAnnouncements} empty={<EmptyState title="No announcements match the current view" />} columns={[{ header: 'Announcement', render: (item) => <div className="max-w-md whitespace-normal"><p className="font-semibold">{item.title}</p><p className="text-xs text-muted">{item.message}</p></div> }, { header: 'Audience', render: (item) => item.audience.replace('_', ' ') }, { header: 'Dates', render: (item) => <span className="text-xs">{item.publish_date}{item.expiry_date ? ` - ${item.expiry_date}` : ''}</span> }, { header: 'Priority', render: (item) => <Badge tone={tone(item.priority)}>{item.priority}</Badge> }, { header: 'Files / state', render: (item) => <div className="flex flex-wrap gap-2"><Button variant="ghost" className="min-h-8 px-2" disabled={saving} onClick={() => void run(() => departmentOperationsRepository.markAnnouncementRead(item.id), 'Announcement marked as read.')}>{item.readBy.includes(currentUser.id) ? 'Read' : 'Mark read'}</Button>{item.attachments.map((attachment) => <Button key={attachment.id} variant="ghost" className="min-h-8 px-2" onClick={() => setPreview(attachment)}><Paperclip className="size-3" /> Preview</Button>)}{item.author_id === currentUser.id && <Button variant="ghost" className="min-h-8 px-2" onClick={() => openAnnouncement(item)}>Edit</Button>}</div> }]} /></div></Card>
    <Modal isOpen={announcementOpen} title={announcement.id ? 'Edit announcement' : 'Publish announcement'} onClose={() => !saving && setAnnouncementOpen(false)}><div className="space-y-3"><label className="text-sm font-semibold">Title<Input className="mt-1" value={announcement.title} onChange={(event) => setAnnouncement({ ...announcement, title: event.target.value })} /></label><label className="text-sm font-semibold">Message<Textarea className="mt-1" value={announcement.message} onChange={(event) => setAnnouncement({ ...announcement, message: event.target.value })} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Audience<Select className="mt-1" value={announcement.audience} onChange={(event) => setAnnouncement({ ...announcement, audience: event.target.value, targetId: '' })}>{announcementAudiences.map((audience) => <option key={audience} value={audience}>{audience.replace('_', ' ')}</option>)}</Select></label><label className="text-sm font-semibold">Priority<Select className="mt-1" value={announcement.priority} onChange={(event) => setAnnouncement({ ...announcement, priority: event.target.value as typeof announcement.priority })}><option value="low">low</option><option value="normal">normal</option><option value="high">high</option></Select></label><label className="text-sm font-semibold">Publish date<Input className="mt-1" type="date" value={announcement.publishDate} onChange={(event) => setAnnouncement({ ...announcement, publishDate: event.target.value })} /></label><label className="text-sm font-semibold">Expiry date<Input className="mt-1" type="date" value={announcement.expiryDate} onChange={(event) => setAnnouncement({ ...announcement, expiryDate: event.target.value })} /></label></div>{announcement.audience === 'assigned_students' && <label className="text-sm font-semibold">Recipient profile IDs<Input className="mt-1" value={announcement.targetId} onChange={(event) => setAnnouncement({ ...announcement, targetId: event.target.value })} placeholder="Comma-separated profile UUIDs" /></label>}<label className="text-sm font-semibold">Category<Input className="mt-1" value={announcement.category} onChange={(event) => setAnnouncement({ ...announcement, category: event.target.value })} /></label><PrivateFileInput label="Optional private attachment" file={announcement.file} onFile={(file) => setAnnouncement({ ...announcement, file })} onError={setActionError} disabled={saving} /><div className="flex justify-end"><Button disabled={saving} onClick={() => void run(async () => { await departmentOperationsRepository.saveAnnouncement(announcement); setAnnouncementOpen(false) }, announcement.id ? 'Announcement updated.' : 'Announcement published.')}>{saving ? 'Saving...' : announcement.id ? 'Save changes' : 'Publish'}</Button></div></div></Modal>
    {preview && <SecureAttachmentPreview attachment={preview} onClose={() => setPreview(null)} />}
  </div>
  const openReview = (item: ComplaintRecord) => {
    const assignedTo = item.assigned_to && complaintAssignees.some((assignee) => assignee.id === item.assigned_to) ? item.assigned_to : ''
    setActionError(''); setReview({ status: item.status === 'resolved' ? 'resolved' : 'in_review', response: item.response ?? '', assignedTo }); setReviewing(item)
  }

  return <div className="space-y-6">
    <PageHeader title="Department operations" description="Live announcements, complaint handling, and direct messages. Private file previews expire after five minutes." actions={<div className="flex flex-wrap gap-2">{canPublish && <Button onClick={() => openAnnouncement()}><Plus className="size-4" /> Announcement</Button>}{canSubmitComplaint && <Button variant="secondary" onClick={() => { setActionError(''); setComplaint(initialComplaint()); setComplaintOpen(true) }}><Plus className="size-4" /> Complaint</Button>}<Button variant="secondary" onClick={() => { setActionError(''); setMessage({ recipientId: '', body: '' }); setMessageOpen(true) }}><Mail className="size-4" /> Message</Button></div>} />
    {(actionError || success) && <div className="space-y-3">{actionError && <ErrorState title="Operation needs attention" description={actionError} />}{success && <div role="status" className="rounded-xl border border-success/30 bg-success/5 p-4 text-sm font-medium text-text">{success}</div>}</div>}
    <Card><div className="grid gap-3 md:grid-cols-[1fr_12rem]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-muted" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search announcements, complaints, or messages" /></label><Select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All announcement audiences</option>{audiences.map((audience) => <option key={audience} value={audience}>{audience.replace('_', ' ')}</option>)}</Select></div></Card>
    <Card><div className="flex items-center gap-3"><Bell className="size-5 text-secondary" /><div><h2 className="font-bold text-text">Announcements</h2><p className="text-sm text-muted">Audience visibility is enforced by Supabase RLS.</p></div></div><div className="mt-4"><DataTable rows={visibleAnnouncements} empty={<EmptyState title="No announcements match the current view" />} columns={[{ header: 'Announcement', render: (item) => <div className="max-w-md whitespace-normal"><p className="font-semibold">{item.title}</p><p className="text-xs text-muted">{item.message}</p></div> }, { header: 'Audience', render: (item) => item.audience.replace('_', ' ') }, { header: 'Dates', render: (item) => <span className="text-xs">{item.publish_date}{item.expiry_date ? ` → ${item.expiry_date}` : ''}</span> }, { header: 'Priority', render: (item) => <Badge tone={tone(item.priority)}>{item.priority}</Badge> }, { header: 'Files / state', render: (item) => <div className="flex flex-wrap gap-2"><Button variant="ghost" className="min-h-8 px-2" disabled={saving} onClick={() => void run(() => departmentOperationsRepository.markAnnouncementRead(item.id), 'Announcement marked as read.')}>{item.readBy.includes(currentUser.id) ? 'Read' : 'Mark read'}</Button>{item.attachments.map((attachment) => <Button key={attachment.id} variant="ghost" className="min-h-8 px-2" onClick={() => setPreview(attachment)}><Paperclip className="size-3" /> Preview</Button>)}{(item.author_id === currentUser.id || canReviewComplaints) && <Button variant="ghost" className="min-h-8 px-2" onClick={() => openAnnouncement(item)}>Edit</Button>}</div> }]} /></div></Card>
    {(canSubmitComplaint || canReviewComplaints) && <Card><div><h2 className="font-bold text-text">Complaints</h2><p className="text-sm text-muted">Resolved complaints are locked in this workflow.</p></div><div className="mt-4"><DataTable rows={visibleComplaints} empty={<EmptyState title="No complaints match the current view" />} columns={[{ header: 'Complaint', render: (item) => <div className="max-w-md whitespace-normal"><p className="font-semibold">{item.subject}</p><p className="text-xs text-muted">{item.description}</p></div> }, { header: 'Status', render: (item) => <Badge tone={tone(item.status)}>{item.status.replace('_', ' ')}</Badge> }, { header: 'History', render: (item) => <span className="text-xs text-muted">Submitted {formatDate(item.created_at)}{item.updated_at !== item.created_at ? ` · Updated ${formatDate(item.updated_at)}` : ''}{item.response ? ` · ${item.response}` : ''}</span> }, { header: 'Files / action', render: (item) => <div className="flex flex-wrap gap-2">{item.attachments.map((attachment) => <Button key={attachment.id} variant="ghost" className="min-h-8 px-2" onClick={() => setPreview(attachment)}><Paperclip className="size-3" /> Preview</Button>)}{canReviewComplaints && <Button variant="ghost" className="min-h-8 px-2" disabled={item.status === 'resolved'} onClick={() => openReview(item)}>{item.status === 'resolved' ? 'Locked' : 'Review'}</Button>}</div> }]} /></div></Card>}
    <MessagePanel messages={visibleMessages} userId={currentUser.id} saving={saving} onRead={(id) => void run(() => departmentOperationsRepository.markMessageRead(id), 'Message marked as read.')} onArchive={(id) => void run(() => departmentOperationsRepository.archiveMessage(id), 'Message archived.')} />
    <Modal isOpen={announcementOpen} title={announcement.id ? 'Edit announcement' : 'Publish announcement'} onClose={() => !saving && setAnnouncementOpen(false)}><div className="space-y-3"><label className="text-sm font-semibold">Title<Input className="mt-1" value={announcement.title} onChange={(event) => setAnnouncement({ ...announcement, title: event.target.value })} /></label><label className="text-sm font-semibold">Message<Textarea className="mt-1" value={announcement.message} onChange={(event) => setAnnouncement({ ...announcement, message: event.target.value })} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Audience<Select className="mt-1" value={announcement.audience} onChange={(event) => setAnnouncement({ ...announcement, audience: event.target.value, targetId: '' })}>{audiences.map((audience) => <option key={audience} value={audience}>{audience.replace('_', ' ')}</option>)}</Select></label><label className="text-sm font-semibold">Priority<Select className="mt-1" value={announcement.priority} onChange={(event) => setAnnouncement({ ...announcement, priority: event.target.value as typeof announcement.priority })}><option value="low">low</option><option value="normal">normal</option><option value="high">high</option></Select></label><label className="text-sm font-semibold">Publish date<Input className="mt-1" type="date" value={announcement.publishDate} onChange={(event) => setAnnouncement({ ...announcement, publishDate: event.target.value })} /></label><label className="text-sm font-semibold">Expiry date<Input className="mt-1" type="date" value={announcement.expiryDate} onChange={(event) => setAnnouncement({ ...announcement, expiryDate: event.target.value })} /></label></div>{(announcement.audience === 'section' || announcement.audience === 'assigned_students') && <label className="text-sm font-semibold">{announcement.audience === 'section' ? 'Section ID' : 'Recipient profile IDs'}<Input className="mt-1" value={announcement.targetId} onChange={(event) => setAnnouncement({ ...announcement, targetId: event.target.value })} placeholder={announcement.audience === 'section' ? 'Section UUID' : 'Comma-separated profile UUIDs'} /></label>}<label className="text-sm font-semibold">Category<Input className="mt-1" value={announcement.category} onChange={(event) => setAnnouncement({ ...announcement, category: event.target.value })} /></label><PrivateFileInput label="Optional private attachment" file={announcement.file} onFile={(file) => setAnnouncement({ ...announcement, file })} onError={setActionError} disabled={saving} /><div className="flex justify-end"><Button disabled={saving} onClick={() => void run(async () => { await departmentOperationsRepository.saveAnnouncement(announcement); setAnnouncementOpen(false) }, announcement.id ? 'Announcement updated.' : 'Announcement published.')}>{saving ? 'Saving…' : announcement.id ? 'Save changes' : 'Publish'}</Button></div></div></Modal>
    <Modal isOpen={complaintOpen} title="Submit complaint" onClose={() => !saving && setComplaintOpen(false)}><div className="space-y-3"><label className="text-sm font-semibold">Category<Select className="mt-1" value={complaint.category} onChange={(event) => setComplaint({ ...complaint, category: event.target.value })}><option>Infrastructure</option><option>Academic</option><option>Harassment</option><option>Other</option></Select></label><label className="text-sm font-semibold">Subject<Input className="mt-1" value={complaint.subject} onChange={(event) => setComplaint({ ...complaint, subject: event.target.value })} /></label><label className="text-sm font-semibold">Description<Textarea className="mt-1" value={complaint.description} onChange={(event) => setComplaint({ ...complaint, description: event.target.value })} /></label><PrivateFileInput label="Optional private attachment" file={complaint.file} onFile={(file) => setComplaint({ ...complaint, file })} onError={setActionError} disabled={saving} /><div className="flex justify-end"><Button disabled={saving} onClick={() => void run(async () => { await departmentOperationsRepository.submitComplaint(complaint); setComplaintOpen(false) }, 'Complaint submitted.')}>{saving ? 'Submitting…' : 'Submit complaint'}</Button></div></div></Modal>
    <Modal isOpen={Boolean(reviewing)} title="Review complaint" onClose={() => !saving && setReviewing(null)}><div className="space-y-3"><label className="text-sm font-semibold">Status<Select className="mt-1" value={review.status} onChange={(event) => setReview({ ...review, status: event.target.value as typeof review.status })}><option value="in_review">in review</option><option value="resolved">resolved</option></Select></label><label className="text-sm font-semibold">Assign to active user (optional)<Select className="mt-1" value={review.assignedTo} onChange={(event) => setReview({ ...review, assignedTo: event.target.value })}><option value="">Unassigned</option>{complaintAssignees.map((recipient) => <option key={recipient.id} value={recipient.id}>{recipient.full_name} · {recipient.role}</option>)}</Select></label><label className="text-sm font-semibold">Response<Textarea className="mt-1" value={review.response} onChange={(event) => setReview({ ...review, response: event.target.value })} /></label><div className="flex justify-end"><Button disabled={saving || !reviewing} onClick={() => { if (reviewing) void run(async () => { await departmentOperationsRepository.reviewComplaint({ id: reviewing.id, status: review.status, response: review.response, assignedTo: review.assignedTo || null }); setReviewing(null) }, 'Complaint updated.') }}>{saving ? 'Saving…' : 'Save review'}</Button></div></div></Modal>
    <Modal isOpen={messageOpen} title="Send message" onClose={() => !saving && setMessageOpen(false)}><div className="space-y-3"><label className="text-sm font-semibold">Recipient<Select className="mt-1" value={message.recipientId} onChange={(event) => setMessage({ ...message, recipientId: event.target.value })}><option value="">Select an active department user</option>{records.recipients.filter((recipient) => recipient.id !== currentUser.id).map((recipient) => <option key={recipient.id} value={recipient.id}>{recipient.full_name} · {recipient.role}</option>)}</Select></label><label className="text-sm font-semibold">Message<Textarea className="mt-1" value={message.body} onChange={(event) => setMessage({ ...message, body: event.target.value })} /></label><div className="flex justify-end"><Button disabled={saving} onClick={() => void run(async () => { await departmentOperationsRepository.sendMessage({ recipientId: message.recipientId, message: message.body }); setMessageOpen(false) }, 'Message sent.')}>{saving ? 'Sending…' : 'Send message'}</Button></div></div></Modal>
    {preview && <SecureAttachmentPreview attachment={preview} onClose={() => setPreview(null)} />}
  </div>
}

function audienceTarget(item: AnnouncementRecord) {
  if (item.audience === 'section' && typeof item.target === 'object' && item.target !== null && !Array.isArray(item.target) && typeof item.target.section_id === 'string') return item.target.section_id
  if (item.audience === 'assigned_students' && typeof item.target === 'object' && item.target !== null && !Array.isArray(item.target) && Array.isArray(item.target.profile_ids)) return item.target.profile_ids.filter((id): id is string => typeof id === 'string').join(', ')
  return ''
}

function StudentAnnouncements({ records, userId, query, setQuery, filter, setFilter, saving, run, reload, preview, setPreview }: { records: OperationsData; userId: string; query: string; setQuery: (value: string) => void; filter: string; setFilter: (value: string) => void; saving: boolean; run: (work: () => Promise<void>, notice: string) => Promise<void>; reload: () => Promise<void>; preview: AttachmentRow | null; setPreview: (value: AttachmentRow | null) => void }) {
  const today = new Date().toISOString().slice(0, 10)
  const categories = [...new Set(records.announcements.map((item) => item.category).filter(Boolean))].sort()
  const filtered = records.announcements
    .filter((item) => `${item.title} ${item.message} ${item.category}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || item.category === filter))
    .sort((a, b) => Number(b.priority === 'high') - Number(a.priority === 'high') || b.publish_date.localeCompare(a.publish_date))

  return <div className="space-y-6">
    <PageHeader title="Announcements" description="Official department announcements visible to your authenticated student profile." actions={<Button variant="secondary" onClick={() => void reload()}><RefreshCw className="size-4" /> Refresh</Button>} />
    <Card><div className="grid gap-3 md:grid-cols-[1fr_14rem]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-muted" /><Input aria-label="Search announcements" className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search official announcements" /></label><Select aria-label="Filter category" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All categories</option>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</Select></div></Card>
    {!filtered.length ? <EmptyState title="No announcements match" description="Official announcements available to your student profile will appear here." /> : <div className="grid gap-4 lg:grid-cols-2">{filtered.map((item) => {
      const read = item.readBy.includes(userId)
      const expired = Boolean(item.expiry_date && item.expiry_date < today)
      const author = records.recipients.find((profile) => profile.id === item.author_id)?.full_name ?? 'Department'
      return <article key={item.id} className={`rounded-lg border p-4 ${read ? 'border-border bg-surface' : 'border-primary/40 bg-primary/5'} ${expired ? 'opacity-75' : ''}`}>
        <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap gap-2"><Badge tone={item.priority === 'high' ? 'warning' : 'primary'}>{item.priority === 'high' ? 'Pinned' : item.priority}</Badge><Badge tone={read ? 'success' : 'warning'}>{read ? 'Read' : 'Unread'}</Badge><Badge tone={expired ? 'muted' : 'success'}>{expired ? 'Expired' : 'Active'}</Badge></div><h2 className="mt-3 font-bold text-text">{item.title}</h2></div><span className="text-xs font-semibold text-muted">{item.category}</span></div>
        <p className="mt-3 whitespace-pre-wrap text-sm text-text">{item.message}</p>
        <div className="mt-4 grid gap-2 text-xs text-muted sm:grid-cols-3"><span>Publisher: {author}</span><span>Published: {item.publish_date}</span><span>Expires: {item.expiry_date ?? 'No expiry'}</span></div>
        <div className="mt-4 flex flex-wrap gap-2"><Button variant="ghost" className="min-h-8 px-2" disabled={saving || read} onClick={() => void run(() => departmentOperationsRepository.markAnnouncementRead(item.id), 'Announcement marked as read.')}>{read ? 'Read' : 'Mark read'}</Button>{item.attachments.map((attachment) => <Button key={attachment.id} variant="ghost" className="min-h-8 px-2" onClick={() => setPreview(attachment)}><Paperclip className="size-3" /> Attachment</Button>)}{!item.attachments.length && <span className="text-xs text-muted">No attachment</span>}</div>
      </article>
    })}</div>}
    {preview && <SecureAttachmentPreview attachment={preview} onClose={() => setPreview(null)} />}
  </div>
}

function formatDate(value: string) { return new Date(value).toLocaleString() }

function MessagePanel({ messages, userId, saving, onRead, onArchive }: { messages: MessageRecord[]; userId: string; saving: boolean; onRead: (id: string) => void; onArchive: (id: string) => void }) {
  const inbox = messages.filter((item) => item.recipient_id === userId && !item.archived_at)
  const sent = messages.filter((item) => item.sender_id === userId)
  return <Card><div><h2 className="font-bold text-text">Messages</h2><p className="text-sm text-muted">Inbox {inbox.length} · Sent {sent.length}. The live schema supports direct messages only.</p></div><div className="mt-4"><DataTable rows={inbox} empty={<EmptyState title="No inbox messages" />} columns={[{ header: 'Message', render: (item) => <div className="max-w-lg whitespace-normal">{item.message}</div> }, { header: 'Received', render: (item) => formatDate(item.created_at) }, { header: 'State', render: (item) => <Badge tone={tone(item.read_at ? 'read' : 'unread')}>{item.read_at ? 'read' : 'unread'}</Badge> }, { header: 'Action', render: (item) => <div className="flex gap-2"><Button disabled={saving || Boolean(item.read_at)} className="min-h-8 px-2" variant="ghost" onClick={() => onRead(item.id)}>Read</Button><Button disabled={saving} className="min-h-8 px-2" variant="ghost" onClick={() => onArchive(item.id)}>Archive</Button></div> }]} /></div></Card>
}
