export type { AuthSession, FacultyResponsibility, UserRole, UserStatus } from '@/types/auth.types'
export type { AcademicTerm, DepartmentProgram } from '@/types/academic.types'
export type { NavigationItem } from '@/types/navigation.types'
export type { AppUser } from '@/types/user.types'
export type { DashboardItem, DashboardMetric, DashboardQuickAction, DashboardSection, DashboardSectionKind, DashboardTone, RoleDashboardData } from '@/types/dashboard.types'
export type { AcademicYear, AllocationDraft, ClassSection, Semester, Subject, SubjectAllocation, TimetableDraft, TimetableEntry, UserDraft } from '@/types/erp.types'
export type { AttendanceCorrection, AttendanceRecord, AttendanceSession, AttendanceStatus, CorrectionDecision, DailyCheckIn, StaffAttendance } from '@/types/attendance.types'
export type { Assessment, AssessmentDraft, AssessmentState, AssessmentType, MarkCorrection, MarkEntry } from '@/types/marks.types'
export type { DepartmentRequest, RequestDraft, RequestHistory, RequestKind, RequestStatus } from '@/types/request.types'
export type { Announcement, AnnouncementAudience, Complaint, InternalMessage } from '@/types/communication.types'
export type { AuditRecord, PortionCompletion } from '@/types/admin.types'
export type { DocumentAttachmentReview, DocumentReviewDecision, DocumentVerificationStatus, FacultyJuryEligibility } from '@/types/attachment.types'
export { DOCUMENT_VERIFICATION_STATUSES } from '@/types/attachment.types'
